name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone java-repo-one repository
      run: |
        cd D:\a\java-repo-two\java-repo-two
        git clone https://github.com/NITHIN-K-BHAT/java-repo-one.git
        cp -r java-repo-one\* .

    - name: Compile and run Java program
      run: |
        javac DitaMapProcessor.java
        java DitaMapProcessor

    - name: Detect changes in specific files
      id: detect-changes
      run: |
        git fetch
        # Get the list of changed files between the current commit and the previous commit
        git diff --name-only HEAD~1 HEAD > changed_files.txt
        # Create a directory to store the changed files
        mkdir changed_files
        # Copy each changed file to the 'changed_files' directory
        foreach ($file in Get-Content changed_files.txt) {
          Copy-Item -Path $file -Destination changed_files -Force
        }
      shell: pwsh

    - name: Upload output files
      uses: actions/upload-artifact@v2
      with:
        name: dita-output-files
        path: D:\a\java-repo-two\java-repo-two/*.dita

    - name: Upload changed files
      uses: actions/upload-artifact@v2
      with:
        name: changed-files
        path: D:\a\java-repo-two\java-repo-two\changed_files\
