name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone java-repo-one repository
      run: |
        cd D:\a\java-repo-two\java-repo-two
        git clone https://github.com/NITHIN-K-BHAT/java-repo-one.git
        cp -r java-repo-one\* .

    - name: Compile and run Java program
      run: |
        javac DitaMapProcessor.java
        java DitaMapProcessor

    - name: Detect changes in specific files
      id: detect-changes
      run: |
        git fetch
        # Handle the case for the first commit on the branch
        git diff --name-only HEAD~1 HEAD > changed_files.txt || echo "No previous commit"
        $changedFiles = Get-Content changed_files.txt
        $specificFile = "specific-file.txt"
        if ($changedFiles -contains $specificFile) {
          Add-Content -Path changed_files.txt -Value $specificFile
        }
      shell: pwsh

    - name: Upload output files
      uses: actions/upload-artifact@v2
      with:
        name: dita-output-files
        path: D:\a\java-repo-two\java-repo-two/*.dita

    - name: Upload changed files
      if: always()  # Ensures this step runs even if the previous step fails
      uses: actions/upload-artifact@v2
      with:
        name: changed-files
        path: D:\a\java-repo-two\java-repo-two/changed_files.txt
