name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone java-repo-one repository
      run: |
       mkdir ak
       cd ak
       git clone https://github.com/NITHIN-K-BHAT/java-repo-one.git
       ls
       dir
       cd java-repo-one
       ls
       dir
       cat DitaMapProcessor.java
       

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: '17.0.11'
        
    - name: Compile Java code
      run: |
              cd ak     
              java -version
              dir
              ls 
              pwd
         

      
    - name: Run Java code
      run: | 
          pwd
          dir
          cd ak
          cd java-repo-one
          java DitaMapProcessor

    - name: Upload output files
      uses: actions/upload-artifact@v2
      with:
        name: dita-output-files
        path: java-repo-one/*.dita
