name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Clone java-repo-one repository
        run: |
          cd D:\a\java-repo-two\java-repo-two
          git clone https://github.com/NITHIN-K-BHAT/java-repo-one.git
          cd java-repo-one
          cp -r ./* ../
          cd ..
          javac DitaMapProcessor.java
          java DitaMapProcessor

      - name: Check diff for specific file
        run: |
          cd D:\a\java-repo-two\java-repo-two
          git diff main^ main -- java-repo-one/* || echo "No changes"

      - name: Upload output files
        uses: actions/upload-artifact@v2
        with:
          name: dita-output-files
          path: D:\a\java-repo-two\java-repo-two/*.dita
