name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

     
      

    - name: Clone java-repo-one repository
      run: |
       
       dir
       ls
       cd  D:\a\java-repo-two\java-repo-two
       git clone https://github.com/NITHIN-K-BHAT/java-repo-one.git
       ls
       dir
       
       cd java-repo-one
       ls
       dir
       pwd
       cd D:\a\java-repo-two\java-repo-two
       cp -r java-repo-one\* .

       javac DitaMapProcessor.java
       java DitaMapProcessor
          
       cat DitaMapProcessor.java

    - name: Upload output files
      uses: actions/upload-artifact@v2
      with:
        name: dita-output-files
        path: java-repo-one/*.dita

       

