name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

     
      

    - name: Clone java-repo-one repository
      run: |
       
       dir
       ls

       git clone https://github.com/NITHIN-K-BHAT/java-repo-one.git
       ls
       dir
       
       cd java-repo-one
       ls
       dir
       pwd
       javac DitaMapProcessor.java
          java DitaMapProcessor
          
       cat DitaMapProcessor.java
       

